version: "3.7"
services:
  webapi:
    build:
      context: .
      dockerfile: atlas/Dockerfile
    container_name: webapi
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./atlas/.env
    networks:
      - ohdsi-network

  atlas:
    image: ohdsi/atlas:latest
    container_name: atlas
    ports:
      - "8180:8080"
    environment:
      - WEBAPI_URL=http://localhost:8080/WebAPI
#      - ATLAS_USER_AUTH_ENABLED=true
    depends_on:
      - webapi
    networks:
      - ohdsi-network

networks:
  ohdsi-network:
    name: etl-ohdsi-network
    external: true