version: '3.8'

services:

  sqlmesh-db:
    container_name: sqlmesh-db
    image: mariadb:10.11.7
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
      MYSQL_ROOT_PASSWORD: openmrs
    volumes:
      - db-data:/var/lib/mysql
      - ./omrs-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - ohdsi-network

  core:
    build: core
    image: omop-etl-core
    container_name: core
    environment:
      SRC_HOST: sqlmesh-db
      SRC_PORT: 3306
      SRC_USER: openmrs
      SRC_PASS: openmrs
      SRC_DB: openmrs
      SQLMESH_DB_ROOT_PASSWORD: openmrs
      TARGET_HOST: omop-db
      TARGET_PORT: 5432
      TARGET_USER: postgres
      TARGET_PASS: postgres_pass
      TARGET_DB: postgres
      ACHILLES_VOCAB_SCHEMA: public
      ACHILLES_RESULTS_SCHEMA: cdm_results
      ATLAS_WEB_API_SCHEMA: webapi
    depends_on:
      - sqlmesh-db
      - omop-db

    volumes:
       - ./concepts:/concepts
      # Uncomment the following line during development to mount local files and see changes without rebuilding the image.
      # Note: This will override files copied into /core during build.
      # - so be sure your local files are complete.
       - ./core:/core
    profiles:
      - manual
    networks:
      - ohdsi-network

  omop-db:
    image: ghcr.io/ohdsi/omop-etl-postgresdb:${OMOP_PG_DB_VERSION}
    container_name: omop-db
    restart: always
    shm_size: 2gb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ohdsi-network

  achilles:
    build: achilles
    image: omop-etl-achilles
    container_name: achilles
    platform: linux/amd64
    depends_on:
      - omop-db
    environment:
      ACHILLES_DB_URI: "postgresql://omop-db:5432/postgres"
      ACHILLES_DB_USERNAME: "postgres"
      ACHILLES_DB_PASSWORD: "postgres_pass"
      ACHILLES_CDM_SCHEMA: "public"
      ACHILLES_VOCAB_SCHEMA: "public"
      ACHILLES_RESULTS_SCHEMA: "cdm_results"
      ACHILLES_CDM_VERSION: "5.4"
      ACHILLES_NUM_THREADS: "1"
    profiles:
      - manual
    networks:
      - ohdsi-network

  dqd:
    build: dqd
    image: omop-etl-dqd
    container_name: omop-etl-dqd
    depends_on:
      - omop-db
    platform: "linux/amd64"
#    secrets:
#      - CDM_CONNECTIONDETAILS_PASSWORD
    env_file:
      - .env
    volumes:
      - jdbc-drivers-data:/jdbc
      - cdm-postprocessing-data:/postprocessing
    profiles:
      - manual
    networks:
      - ohdsi-network

  dqd-viewer:
    image: omop-etl-dqd
    container_name: omop-etl-dqd-viewer
    depends_on:
      - omop-db
    env_file:
      - .env
    profiles:
      - manual
    ports:
      - "3000:3000"
    volumes:
      - jdbc-drivers-data:/jdbc
      - cdm-postprocessing-data:/postprocessing
    command: [ "Rscript", "/opt/dqd/run_dqd.R", "view" ]

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    depends_on:
      - sqlmesh-db
      - omop-db
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - ohdsi-network
    profiles:
      - manual

volumes:
  db-data: ~
  postgres_data: ~
  jdbc-drivers-data: ~
  cdm-postprocessing-data:
    name: cdm-postprocessing-data
  cloudbeaver-data: ~

networks:
  ohdsi-network:
    name: etl-ohdsi-network
    driver: bridge