import logging
import os
from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.sensors.python import PythonSensor
from docker.types import Mount
from docker_utils import create_core_docker_task

default_args = {
    'owner': 'you',
    'retries': 1,
    'retry_delay': timedelta(minutes=2)
}


def check_mapping_has_data():
    log = logging.getLogger("airflow.task")
    file_path = '/opt/concepts/autogenerated_omop_mappings.csv'

    if not os.path.exists(file_path):
        log.info(f"Sensor check: File NOT found at {file_path} samuel")
        return False
    try:
        with open(file_path, 'r') as f:
            # We use readlines() as you requested for the > 20 check
            lines = f.readlines()
            line_count = len(lines)

            if line_count > 20:
                log.info(f"Sensor SUCCESS: Found {line_count} rows. Proceeding...")
                return True
            else:
                log.info(f"Sensor PENDING: Found {line_count} rows (Need > 20). Rescheduling...")
                return False

    except Exception as e:
        log.error(f"Error reading mapping file: {str(e)}")
        return False

with DAG(
        dag_id='OpenMRS_to_OMOP_Clinical_ETL',
        default_args=default_args,
        start_date=datetime(2026, 1, 1),
        schedule='0 */8 * * *',  # Every 8 hours
        catchup=False,
        tags=['OMOP', 'Clinical', 'Daily']
) as dag:
    apply_sqlmesh_plan = create_core_docker_task("apply_sqlmesh_plan", "apply-sqlmesh-plan")
    materialize_mysql_views = create_core_docker_task("materialize_mysql_views", "materialize-mysql-views")
    migrate_to_postgresql = create_core_docker_task("migrate_to_postgresql", "migrate-to-postgresql")

    wait_for_vocab = PythonSensor(
        task_id='wait_for_vocabulary',
        python_callable=check_mapping_has_data,
        mode='reschedule',
        poke_interval=60,
        timeout=7200
    )


    run_achilles = DockerOperator(
        task_id='achilles',
        image='omop-etl-achilles',
        api_version='auto',
        auto_remove='success',
        docker_url='unix://var/run/docker.sock',
        network_mode='etl-ohdsi-network',
        command="Rscript /opt/achilles/entrypoint.r",
        environment={
            'ACHILLES_DB_URI': 'postgresql://omop-db:5432/postgres',
            'ACHILLES_DB_USERNAME': 'postgres',
            'ACHILLES_DB_PASSWORD': 'postgres_pass',
            'ACHILLES_CDM_SCHEMA': 'public',
            'ACHILLES_VOCAB_SCHEMA': 'public',
            'ACHILLES_RESULTS_SCHEMA': 'cdm_results',
            'ACHILLES_CDM_VERSION': '5.4',
            'ACHILLES_NUM_THREADS': '1'
        }
    )

    run_dqd = DockerOperator(
        task_id='dqd_run',
        image='omop-etl-dqd',
        api_version='auto',
        auto_remove='success',
        docker_url='unix://var/run/docker.sock',
        network_mode='etl-ohdsi-network',
        command='Rscript /opt/dqd/run_dqd.R run',
        mounts=[
            Mount(source="jdbc-drivers-data", target="/jdbc", type="volume"),
            Mount(source="cdm-postprocessing-data", target="/postprocessing", type="volume")
        ],
        environment={
            'CDM_CONNECTIONDETAILS_DBMS': "postgresql",
            'CDM_CONNECTIONDETAILS_USER': "postgres",
            'CDM_CONNECTIONDETAILS_SERVER': "omop-db/postgres",
            'CDM_CONNECTIONDETAILS_PORT': "5432",
            'CDM_CONNECTIONDETAILS_PASSWORD': "postgres_pass",
            'CDM_CONNECTIONDETAILS_EXTRA_SETTINGS': "",
            'CDM_VERSION': "5.4",
            'CDM_SOURCE_NAME': "OpenMRS",
            'CDM_DATABASE_SCHEMA': "public",
            'RESULTS_DATABASE_SCHEMA': "cdm_results",
            'VOCAB_DATABASE_SCHEMA': "public",
            'DQD_NUM_THREADS': "1",
            'DQD_SQL_ONLY': "FALSE",
            'DQD_SQL_ONLY_UNION_COUNT': "1",
            'DQD_SQL_ONLY_INCREMENTAL_INSERT': "FALSE",
            'DQD_VERBOSE_MODE': "TRUE",
            'DQD_WRITE_TO_TABLE': "TRUE",
            'DQD_WRITE_TABLE_NAME': "dqdashboard_results",
            'DQD_WRITE_TO_CSV': "FALSE",
            'DQD_CSV_FILE': "",
            'DQD_CHECK_LEVELS': "TABLE,FIELD,CONCEPT",
            'DQD_CHECK_NAMES': "",
            'DQD_COHORT_DEFINITION_ID': "",
            'DQD_COHORT_DATABASE_SCHEMA': "public",
            'DQD_COHORT_TABLE_NAME': "cohort",
            'DQD_TABLES_TO_EXCLUDE': "CONCEPT,VOCABULARY,CONCEPT_ANCESTOR,CONCEPT_RELATIONSHIP,CONCEPT_CLASS,CONCEPT_SYNONYM,RELATIONSHIP,DOMAIN",
            'DQD_TABLE_CHECK_THRESHOLD_LOC': "default",
            'DQD_FIELD_CHECK_THRESHOLD_LOC': "default",
            'DQD_CONCEPT_CHECK_THRESHOLD_LOC': "default"
        }
    )

    generate_mapping_report = create_core_docker_task(
        task_id="generate_data_quality_report",
        command="automated-mapping-summary-report"
    )

(       wait_for_vocab
         >> apply_sqlmesh_plan
        >> materialize_mysql_views
        >> migrate_to_postgresql
        >> run_achilles
        >> run_dqd
        >> generate_mapping_report
)
