import logging
import os
import sys

import pandas as pd
import requests
from sqlalchemy import create_engine, text, bindparam

MYSQL_USER="root"
MYSQL_PASSWORD="openmrs"
MYSQL_HOST="sqlmesh-db"
MYSQL_PORT="3306"
MYSQL_DATABASE= "openmrs"
TARGET_HOST="omop-db"
TARGET_USER="omop"
TARGET_PASSWORD="omop"
TARGET_Port="5432"
TARGET_DB="omop"

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s',
    stream=sys.stdout
)
logger = logging.getLogger(__name__)

MYSQL_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"

PG_URL = f"postgresql+psycopg2://{TARGET_USER}:{TARGET_PASSWORD}@{TARGET_HOST}:{TARGET_Port}/{TARGET_DB}"

OCL_API_URL = "https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/"
CONCEPT_DIR = "../concepts/"
AUTO_GEN_MAPPINGS = CONCEPT_DIR + "autogenerated_omop_mappings.csv"
USAGI_MAPPING_FILE = CONCEPT_DIR + "concepts_for_usagi_mapping.csv"

CHUNK_SIZE = 250

def typecasting_floats(value):
    if pd.isna(value) or value == '':
        return None
    return int(float(value))

OPENMRS_EXTRACT_QUERY = text("""
WITH ConceptFrequency AS (
    SELECT 
        concept_id, 
        COUNT(*) AS freq
    FROM obs
    WHERE voided = 0
    GROUP BY concept_id
),

RankedMappings AS (
    SELECT 
        c.concept_id,
        cn.name AS concept_name,
        cl.name AS concept_class,
        rs.name AS source_system,
        rt.code AS source_code,
        ROW_NUMBER() OVER (
            PARTITION BY c.concept_id 
            ORDER BY 
                CASE 
                    WHEN rs.name = 'CIEL' THEN 1 
                    WHEN rs.name IS NOT NULL THEN 2 
                    ELSE 3 
                END
        ) AS rank_id
    FROM concept c
    LEFT JOIN concept_name cn 
        ON c.concept_id = cn.concept_id 
        AND cn.locale = 'en' 
        AND cn.concept_name_type = 'FULLY_SPECIFIED' 
        AND cn.voided = 0
    LEFT JOIN concept_class cl 
        ON c.class_id = cl.concept_class_id
    LEFT JOIN concept_reference_map crm 
        ON c.concept_id = crm.concept_id
    LEFT JOIN concept_reference_term rt 
        ON crm.concept_reference_term_id = rt.concept_reference_term_id
    LEFT JOIN concept_reference_source rs 
        ON rt.concept_source_id = rs.concept_source_id
    WHERE c.retired = 0
)

SELECT 
    rm.concept_id AS source_concept_id,
    rm.concept_name AS source_concept_name,
    rm.concept_class AS type,
    rm.source_system AS "Reference code system",
    rm.source_code AS "Reference code",
    COALESCE(cf.freq, 0) AS frequency,
    CASE
        WHEN rm.source_system = 'CIEL' THEN 'MAPPED TO CIEL'
        WHEN rm.source_system IS NOT NULL THEN 'MAPPED OTHER'
        ELSE 'TRUE ORPHAN'
    END AS "Mapping Status"
FROM RankedMappings rm
LEFT JOIN ConceptFrequency cf 
    ON rm.concept_id = cf.concept_id
WHERE rm.rank_id = 1
ORDER BY frequency DESC; """)

ATHENA_BATCH_LOOKUP_QUERY = text("""
SELECT 
    c1.concept_id AS athena_source_id,
    c1.concept_code AS source_code,
    c1.concept_name AS source_name,
    c1.vocabulary_id AS source_vocab,
    COALESCE(c2.concept_id, 0) AS target_concept_id,
    COALESCE(c2.concept_name, 'No matching concept') AS target_name,
    c1.domain_id AS source_domain,

    CASE
        WHEN c2.concept_id IS NULL
            THEN 'UNMAPPED'

        WHEN COUNT(c2.concept_id) OVER (PARTITION BY c1.concept_id) = 1
            THEN 'MAPPED'

        WHEN COUNT(c2.concept_id) OVER (PARTITION BY c1.concept_id) > 1
             AND COUNT(
                    CASE
                        WHEN c2.standard_concept = 'S' THEN 1
                    END
                 ) OVER (PARTITION BY c1.concept_id) = 1
            THEN 'MULTIPLE_WITH_PRIMARY'

        ELSE 'AMBIGUOUS_MULTIPLE'
    END AS triage_status

FROM concept c1

LEFT JOIN concept_relationship cr
    ON c1.concept_id = cr.concept_id_1
    AND cr.relationship_id = 'Maps to'
    AND cr.invalid_reason IS NULL

LEFT JOIN concept c2
    ON cr.concept_id_2 = c2.concept_id
    AND c2.standard_concept = 'S'
    AND c2.invalid_reason IS NULL

WHERE (c1.concept_code, c1.vocabulary_id) IN :code_vocab_pairs;  """).bindparams(
    bindparam("code_vocab_pairs", expanding=True)
)


def get_ocl_mapping(concept_code):
    """Hits OCL API as a fallback for CIEL codes."""
    try:
        logger.debug(f"Requesting OCL mapping for CIEL:{concept_code}")
        response = requests.get(f"{OCL_API_URL}{concept_code}/", timeout=10)
        if response.status_code == 200:
            mappings = response.json().get('mappings', [])
            if mappings:
               for m in mappings:
                 if m.get('map_type') in ['SAME-AS', 'MAPS-TO']:
                        # Clean up vocab name (e.g. SNOMED-CT -> SNOMED)
                        target_vocab = m.get('to_source_url').split('/')[-2].split('-')[0].upper()
                        return {"code": m.get('to_concept_code'), "vocab": target_vocab}
            else:
                logger.info(f"CIEL:{concept_code} without other relationship mappings")
                return {
                    "code": concept_code,
                    "vocab": "CIEL"
                }
        else:
            logger.warning(f"[OCL SKIP] No mapping found for {concept_code} (Status: {response.status_code})")
    except Exception as e:
        logger.error(f"[OCL ERROR] Connection failed for {concept_code}: {str(e)}")
        return None
    return None


def run_concepts_sematic_mapping():
    logger.info("Starting OpenMRS-to-OMOP concepts sematic Mapping")

    try:
        my_engine = create_engine(MYSQL_URL)
        pg_engine = create_engine(PG_URL)

        logger.info("Step 1: Connecting to MySQL and extracting concepts...")
        with my_engine.connect() as conn:
            df = pd.read_sql(OPENMRS_EXTRACT_QUERY, conn)
        logger.info(f"Extracted {len(df)} unique concepts from OpenMRS.")

        vocab_map = {
            'CIEL': 'CIEL',
            'SNOMED CT': 'SNOMED',
            'LOINC': 'LOINC',
            'ICD-10-WHO': 'ICD10',
            'RxNORM': 'RxNorm',
            'PIH': 'CIEL',
            'AMPATH': 'CIEL'
        }
        df['athena_vocab'] = df['Reference code system'].map(lambda x: vocab_map.get(x, x))
        all_results = []

        logger.info(f"Step 2: Batch Processing Athena codes in chunks of {CHUNK_SIZE}...")

        with pg_engine.connect() as pg_conn:
            for start in range(0, len(df), CHUNK_SIZE):
                chunk = df.iloc[start: start + CHUNK_SIZE].copy()

                # Filter out orphans for the DB query
                valid_chunk = chunk[chunk['Mapping Status'] != 'TRUE ORPHAN']
                pairs = list(valid_chunk[['Reference code', 'athena_vocab']].itertuples(index=False, name=None))

                if pairs:
                    res = pg_conn.execute(ATHENA_BATCH_LOOKUP_QUERY, {"code_vocab_pairs": tuple(pairs)})
                    athena_df = pd.DataFrame(res.fetchall(), columns=res.keys())

                    # Use 'left' merge and explicitly handle the suffixes
                    chunk = chunk.merge(athena_df, left_on=['Reference code', 'athena_vocab'],
                                        right_on=['source_code', 'source_vocab'], how='left')

                for idx, row in chunk.iterrows():
                    record = row.to_dict()
                    target_id = 0
                    match_status = "UNKNOWN"
                    # Ensure we have a clean target_concept_id even if merge failed

                    if row['Mapping Status'] == 'TRUE ORPHAN':
                        target_id = 0
                        match_status = "USAGI_REQUIRED"

                    elif pd.notnull(row.get('athena_source_id')):
                        # Standard Athena Success
                        is_standard = row['target_concept_id'] != 0
                        target_id = typecasting_floats(row['target_concept_id'] if is_standard else row['athena_source_id'])
                        match_status = "SUCCESS_ATHENA" if is_standard else "NON_STANDARD_TAKEUP"

                    elif row['Reference code system'] == 'CIEL':
                        # Fallback to OCL for CIEL only
                        ocl_res = get_ocl_mapping(row['Reference code'])
                        if ocl_res:
                            # Re-verify OCL result against local Athena
                            # IMPORTANT: Use .fetchone() and handle the resulting Row object
                            athena_ocl = pg_conn.execute(ATHENA_BATCH_LOOKUP_QUERY,
                                                         {"code_vocab_pairs": (
                                                             (str(ocl_res['code']), ocl_res['vocab']),)}).fetchone()
                            if athena_ocl:
                                # Row indexing: athena_ocl[3] is target_concept_id
                                target_id = athena_ocl[3] if athena_ocl[3] != 0 else athena_ocl[2]
                                match_status = "SUCCESS_OCL_ATHENA"
                            else:
                                match_status = "FAILED_ATHENA_POST_OCL"
                        else:
                            match_status = "FAILED_OCL_API"
                    else:
                        match_status = "FAILED_ATHENA"
                    record.update({
                        "target_concept_id": typecasting_floats(target_id),
                        "match_status": match_status})
                    all_results.append(record)

        logger.info("Step 3: Saving results to CSV...")
        final_df = pd.DataFrame(all_results)
        os.makedirs(os.path.dirname(CONCEPT_DIR), exist_ok=True)
        final_df.to_csv(AUTO_GEN_MAPPINGS, index=False)

        usagi_needed = final_df[final_df['match_status'].str.contains('FAILED|USAGI')]
        if not usagi_needed.empty:
            usagi_needed.to_csv(USAGI_MAPPING_FILE, index=False)
            logger.info(f"📂 Usagi Import File created: {USAGI_MAPPING_FILE} ({len(usagi_needed)} rows)")
        else:
            logger.info("✨ No Usagi mapping required! Everything was automated.")

        logger.info("-" * 30)
        logger.info("SUMMARY OF MATCH STATUS:")
        logger.info(f"\n{final_df['match_status'].value_counts()}")
        logger.info("-" * 30)

    except Exception as e:
        logger.error(f"❌ CRITICAL ERROR in pipeline: {str(e)}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    run_concepts_sematic_mapping()