import pandas as pd
import matplotlib.pyplot as plt
import os
import logging
import sys

plt.switch_backend('Agg')

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s',
    stream=sys.stdout
)
logger = logging.getLogger(__name__)

MAPPING_CSV = "../concepts/autogenerated_omop_mappings.csv"
REPORT_OUTPUT = "../docs/img/mapping_quality_summary.png"

def generate_report():
    if not os.path.exists(MAPPING_CSV):
        logger.error(f"❌ Mapping file not found at {MAPPING_CSV}")
        return

    df = pd.read_csv(MAPPING_CSV)

    if df.empty:
        logger.warning("CSV is empty. No data to visualize.")
        return

    total_unique = len(df)
    success_df = df[df['match_status'].str.contains('SUCCESS', na=False)]
    success_count = len(success_df)

    total_volume = df['frequency'].sum()
    mapped_volume = success_df['frequency'].sum()
    weighted_success = (mapped_volume / total_volume * 100) if total_volume > 0 else 0

    logger.info(f"Total Unique Concepts: {total_unique}")
    logger.info(f"Unique Mapped: {success_count} ({round(success_count / total_unique * 100, 2)}%)")
    logger.info(f"Volume-Weighted Coverage: {round(weighted_success, 2)}% of all clinical observations")

    plt.figure(figsize=(12, 7))
    status_counts = df['match_status'].value_counts()

    status_counts.plot(kind='barh', color=['#1f77b4', '#2ca02c', '#ff7f0e', '#d62728', '#9467bd'])

    plt.title('OMOP Mapping Success', fontsize=14, pad=20)
    plt.xlabel('Number of Unique Concepts', fontsize=12)
    plt.ylabel('Match Status', fontsize=12)
    plt.grid(axis='x', linestyle='--', alpha=0.6)

    plt.text(0.95, 0.05, f'Clinical Volume Coverage: {round(weighted_success, 1)}%',
             transform=plt.gca().transAxes, ha='right', va='bottom',
             bbox=dict(boxstyle='round', facecolor='white', alpha=0.5))

    os.makedirs(os.path.dirname(REPORT_OUTPUT), exist_ok=True)
    plt.tight_layout()
    plt.savefig(REPORT_OUTPUT, dpi=300)
    logger.info(f"chart saved to: {REPORT_OUTPUT}")

if __name__ == "__main__":
    generate_report()