import os
import pandas as pd
import requests
from sqlalchemy import create_engine, text
import time
import logging
import sys

MYSQL_USER="root"
MYSQL_PASSWORD="openmrs"
MYSQL_HOST="sqlmesh-db"
MYSQL_PORT="3306"
MYSQL_DATABASE= "openmrs"
TARGET_HOST="omop_db"
TARGET_USER="omop"
TARGET_PASSWORD="omop"
TARGET_Port="5432"
TARGET_DB="omop"

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s',
    stream=sys.stdout
)
logger = logging.getLogger(__name__)

MYSQL_URL = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"

PG_URL = f"postgresql://{TARGET_USER}:{TARGET_PASSWORD}@{TARGET_HOST}:{TARGET_Port}/{TARGET_DB}"

OUTPUT_PATH = "../concepts/autogenerated_omop_mappings.csv"
OCL_API_URL = "https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/"

OPENMRS_EXTRACT_QUERY = text("""
WITH ConceptFrequency AS (
    SELECT 
        concept_id, 
        COUNT(*) AS freq
    FROM obs
    WHERE voided = 0
    GROUP BY concept_id
),

RankedMappings AS (
    SELECT 
        c.concept_id,
        cn.name AS concept_name,
        cl.name AS concept_class,
        rs.name AS source_system,
        rt.code AS source_code,
        ROW_NUMBER() OVER (
            PARTITION BY c.concept_id 
            ORDER BY 
                CASE 
                    WHEN rs.name = 'CIEL' THEN 1 
                    WHEN rs.name IS NOT NULL THEN 2 
                    ELSE 3 
                END ASC
        ) AS rank_id
    FROM concept c
    LEFT JOIN concept_name cn 
        ON c.concept_id = cn.concept_id 
        AND cn.locale = 'en' 
        AND cn.concept_name_type = 'FULLY_SPECIFIED' 
        AND cn.voided = 0
    LEFT JOIN concept_class cl 
        ON c.class_id = cl.concept_class_id
    LEFT JOIN concept_reference_map crm 
        ON c.concept_id = crm.concept_id
    LEFT JOIN concept_reference_term rt 
        ON crm.concept_reference_term_id = rt.concept_reference_term_id
    LEFT JOIN concept_reference_source rs 
        ON rt.concept_source_id = rs.concept_source_id
    WHERE c.retired = 0
)

SELECT 
    rm.concept_id AS source_concept_id,
    rm.concept_name AS source_concept_name,
    rm.concept_class AS type,
    rm.source_system AS `Reference code system`,
    rm.source_code AS `Reference code`,
    COALESCE(cf.freq, 0) AS frequency,
    CASE
        WHEN rm.source_system = 'CIEL' THEN 'MAPPED TO CIEL'
        WHEN rm.source_system IS NOT NULL THEN 'MAPPED OTHER'
        ELSE 'TRUE ORPHAN'
    END AS `Mapping Status`
FROM RankedMappings rm
LEFT JOIN ConceptFrequency cf 
    ON rm.concept_id = cf.concept_id
WHERE rm.rank_id = 1
ORDER BY frequency DESC; """)

ATHENA_LOOKUP_QUERY = text("""
SELECT 
    c2.concept_id, 
    c2.concept_name, 
    c2.domain_id
FROM concept c1
JOIN concept_relationship cr 
    ON c1.concept_id = cr.concept_id_1
JOIN concept c2 
    ON cr.concept_id_2 = c2.concept_id
WHERE c1.concept_code = :code
  AND c1.vocabulary_id = :vocab
  AND cr.relationship_id = 'Maps to'
  AND c2.invalid_reason IS NULL
LIMIT 1;  """)


def get_ocl_mapping(concept_code):
    """Fallback: Check OCL for the latest CIEL-to-Standard mapping."""
    try:
        logger.debug(f"Requesting OCL mapping for CIEL:{concept_code}")
        response = requests.get(f"{OCL_API_URL}{concept_code}/", timeout=10)
        if response.status_code == 200:
            mappings = response.json().get('mappings', [])
            for m in mappings:
                if m.get('map_type') in ['SAME-AS', 'MAPS-TO']:
                    target_vocab = m.get('to_source_url').split('/')[-2].replace('-CT', '')
                    logger.info(f"   [OCL FOUND] CIEL:{concept_code} -> {target_vocab}:{m.get('to_concept_code')}")
                    return {
                        "code": m.get('to_concept_code'),
                        "vocab": target_vocab
                    }
        else:
            logger.warning(f"   [OCL SKIP] No mapping found for {concept_code} (Status: {response.status_code})")
    except Exception as e:
        logger.error(f"   [OCL ERROR] Connection failed for {concept_code}: {str(e)}")
        return None
    return None


def run_concepts_sematic_mapping():
    logger.info("Starting OpenMRS-to-OMOP concepts sematic Mapping")

    try:
        my_engine = create_engine(MYSQL_URL)
        pg_engine = create_engine(PG_URL)

        logger.info("Step 1: Connecting to MySQL and extracting concepts...")
        with my_engine.connect() as conn:
            df = pd.read_sql(OPENMRS_EXTRACT_QUERY, conn)
        logger.info(f"Extracted {len(df)} unique concepts from OpenMRS.")

        vocab_map = {'CIEL': 'CIEL', 'SNOMED CT': 'SNOMED', 'LOINC': 'LOINC', 'ICD-10-WHO': 'ICD10'}
        results = []

        logger.info(f"Step 2: Processing mappings via Athena & OCL Fallback...")

        with pg_engine.connect() as pg_conn:
            for i, (index, row) in enumerate(df.iterrows()):
                record = row.to_dict()

                # Progress logging every 100 rows
                if i % 100 == 0 and i > 0:
                    logger.info(f"⏳ Progress: {i}/{len(df)} concepts processed...")

                if row['Mapping Status'] == 'TRUE ORPHAN':
                    record.update({"target_concept_id": 0, "match_status": "USAGI_REQUIRED"})
                else:
                    vocab = vocab_map.get(row['Reference code system'], row['Reference code system'])

                    # 2-A: Local Athena
                    res = pg_conn.execute(ATHENA_LOOKUP_QUERY,
                                          {"code": str(row['Reference code']), "vocab": vocab}).fetchone()

                    if res:
                        record.update({"target_concept_id": res.concept_id, "target_domain": res.domain_id,
                                       "match_status": "SUCCESS_ATHENA"})
                    elif row['Mapping Status'] == 'MAPPED TO CIEL':
                        # 2-B: OCL Fallback
                        time.sleep(0.2)
                        ocl_map = get_ocl_mapping(row['Reference code'])
                        if ocl_map:
                            # 2-C: Re-check Athena with OCL info
                            res_ocl = pg_conn.execute(ATHENA_LOOKUP_QUERY,
                                                      {"code": ocl_map['code'], "vocab": ocl_map['vocab']}).fetchone()
                            if res_ocl:
                                record.update(
                                    {"target_concept_id": res_ocl.concept_id, "target_domain": res_ocl.domain_id,
                                     "match_status": "SUCCESS_OCL_ATHENA"})
                            else:
                                record.update({"target_concept_id": 0, "match_status": "FAILED_ATHENA_AFTER_OCL"})
                        else:
                            record.update({"target_concept_id": 0, "match_status": "FAILED_ALL_LOOKUPS"})
                    else:
                        record.update({"target_concept_id": 0, "match_status": "FAILED_ATHENA"})

                results.append(record)

        logger.info("Step 3: Saving results to CSV...")
        final_df = pd.DataFrame(results)
        os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
        final_df.to_csv(OUTPUT_PATH, index=False)

        logger.info(f"Pipeline Complete! Report: {OUTPUT_PATH}")
        logger.info("-" * 30)
        logger.info("SUMMARY OF MATCH STATUS:")
        logger.info(f"\n{final_df['match_status'].value_counts()}")
        logger.info("-" * 30)

    except Exception as e:
        logger.error(f"❌ CRITICAL ERROR in pipeline: {str(e)}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    run_concepts_sematic_mapping()