from pathlib import Path

concepts_dir = Path("../concepts")
concepts_dir.mkdir(exist_ok=True)

mapping_file = concepts_dir / "mapping.csv"
auto_file = concepts_dir / "autogenerated_omop_mappings.csv"

if not mapping_file.exists():
    mapping_file.write_text(
        "sourceCode,sourceName,sourceFrequency,sourceAutoAssignedConceptIds,matchScore,mappingStatus,equivalence,statusSetBy,statusSetOn,conceptId,conceptName,domainId,mappingType,comment,createdBy,createdOn,assignedReviewer"
    )

if not auto_file.exists():
    auto_file.write_text(
        "source_concept_id,source_concept_name,type,Reference code system,Reference code,frequency,Mapping Status,target_concept_id,target_domain,match_status"
    )

print("OCL/OMOP mapper placeholder files have been generated!")